name: generate animation

on:
  schedule:
    - cron: "0 */24 * * *"
  
  workflow_dispatch:
  
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: dlwtja  # 자신의 GitHub 사용자 이름으로 변경
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg  # 다크 모드용 SVG 파일

      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.3.0  # Node.js 20 지원 최신 버전 사용
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # GitHub Personal Access Token 설정
